//! Unused retail member absence and retained social queries; no native parity claim.
#![cfg(feature = "client-retail")]

pub(crate) const RETIREMENT_ASSERTIONS: &str = r#"
assert(rawget(C_QuestOffer, 'GetHideRequiredItemsOnTurnIn') == nil)
assert(C_QuestOffer.GetHideRequiredItemsOnTurnIn == nil)
assert(C_QuestOffer.GetHideRequiredItemsOnTurnIn == nil)
assert(rawget(C_Social, 'GetLastAchievement') == nil)
assert(C_Social.GetLastAchievement == nil)
assert(C_Social.GetLastAchievement == nil)
assert(rawget(C_Social, 'GetLastItem') == nil)
assert(C_Social.GetLastItem == nil)
assert(C_Social.GetLastItem == nil)
assert(rawget(C_Social, 'GetLastScreenshotIndex') == nil)
assert(C_Social.GetLastScreenshotIndex == nil)
assert(C_Social.GetLastScreenshotIndex == nil)
assert(rawget(C_Social, 'GetMaxTweetLength') == nil)
assert(C_Social.GetMaxTweetLength == nil)
assert(C_Social.GetMaxTweetLength == nil)
assert(rawget(C_Social, 'GetScreenshotInfoByIndex') == nil)
assert(C_Social.GetScreenshotInfoByIndex == nil)
assert(C_Social.GetScreenshotInfoByIndex == nil)
assert(rawget(C_Social, 'GetTweetLength') == nil)
assert(C_Social.GetTweetLength == nil)
assert(C_Social.GetTweetLength == nil)
assert(rawget(C_Social, 'IsSocialEnabled') == nil)
assert(C_Social.IsSocialEnabled == nil)
assert(C_Social.IsSocialEnabled == nil)
assert(rawget(C_Social, 'RegisterSocialBrowser') == nil)
assert(C_Social.RegisterSocialBrowser == nil)
assert(C_Social.RegisterSocialBrowser == nil)
assert(rawget(C_Social, 'SetTextureToScreenshot') == nil)
assert(C_Social.SetTextureToScreenshot == nil)
assert(C_Social.SetTextureToScreenshot == nil)
assert(rawget(C_Social, 'TwitterCheckStatus') == nil)
assert(C_Social.TwitterCheckStatus == nil)
assert(C_Social.TwitterCheckStatus == nil)
assert(rawget(C_Social, 'TwitterConnect') == nil)
assert(C_Social.TwitterConnect == nil)
assert(C_Social.TwitterConnect == nil)
assert(rawget(C_Social, 'TwitterDisconnect') == nil)
assert(C_Social.TwitterDisconnect == nil)
assert(C_Social.TwitterDisconnect == nil)
assert(rawget(C_Social, 'TwitterGetMSTillCanPost') == nil)
assert(C_Social.TwitterGetMSTillCanPost == nil)
assert(C_Social.TwitterGetMSTillCanPost == nil)
assert(rawget(C_Social, 'TwitterPostAchievement') == nil)
assert(C_Social.TwitterPostAchievement == nil)
assert(C_Social.TwitterPostAchievement == nil)
assert(rawget(C_Social, 'TwitterPostItem') == nil)
assert(C_Social.TwitterPostItem == nil)
assert(C_Social.TwitterPostItem == nil)
assert(rawget(C_Social, 'TwitterPostMessage') == nil)
assert(C_Social.TwitterPostMessage == nil)
assert(C_Social.TwitterPostMessage == nil)
assert(rawget(C_Social, 'TwitterPostScreenshot') == nil)
assert(C_Social.TwitterPostScreenshot == nil)
assert(C_Social.TwitterPostScreenshot == nil)
assert(type(C_Social.GetFriends) == 'function')
assert(type(C_Social.GetFriendInfo) == 'function')
"#;

#[test]
fn patch_10_0_7_unused_members_stay_absent() {
    let env = wow_ui_sim::lua_api::WowLuaEnv::new().unwrap();
    env.exec(RETIREMENT_ASSERTIONS).unwrap();
}
