local addon = assert(AccWideUIAceAddon, "account-wide UI missing")
local slash = assert(SlashCmdList.ACECONSOLE_AWI, "awi dispatch missing")
assert(addon:SupportsGameFunction("selfCast"), "self-cast sync unsupported")
assert(addon.db.profile.syncToggles.selfCast, "self-cast sync disabled")
SetCVar("autoSelfCast", "0")
slash("save")
assert(addon.db.profile.syncData.selfCast.cvars.autoSelfCast == "0", "save did not capture self-cast")
print("ACCOUNT_UI_WORKFLOW", "saved-zero")
SetCVar("autoSelfCast", "1")
assert(GetCVar("autoSelfCast") == "1", "intermediate change failed")
slash("load")
assert(GetCVar("autoSelfCast") == "0", "load did not restore self-cast")
print("ACCOUNT_UI_WORKFLOW", "restored-zero")
print("ACCOUNT_UI_WORKFLOW", "DONE")
