local db = assert(ClassicCastBarDB, "addon database missing")
local bar = assert(PlayerCastingBarFrame, "player cast bar missing")
local slider = assert(ClassicCastBarForeverScaleSlider, "scale slider missing")
local slash = assert(SlashCmdList.CLASSICCASTBAR, "slash handler missing")
assert(db.scale == 1, "fresh addon scale must retain authored default")
assert(bar:GetScale() == 1, "fresh cast bar scale differs")
slider:SetValue(1.35)
assert(math.abs(db.scale - 1.35) < 0.000001)
assert(math.abs(bar:GetScale() - 1.35) < 0.000001)
assert(tonumber(C_CVar.GetCVar("ClassicCastBarForever_scale")) == 1.35)
assert(ClassicCastBarCharDB.scale == 1.35)
print("CLASSIC_CASTBAR_WORKFLOW", "scale")
slash("icon")
assert(db.showIcon == false)
assert(not bar.Icon:IsShown())
assert(C_CVar.GetCVar("ClassicCastBarForever_icon") == "0")
slash("icon")
assert(db.showIcon == true)
assert(C_CVar.GetCVar("ClassicCastBarForever_icon") == "1")
print("CLASSIC_CASTBAR_WORKFLOW", "icon")
slash("reset")
assert(db.scale == 1 and bar:GetScale() == 1)
assert(tonumber(C_CVar.GetCVar("ClassicCastBarForever_scale")) == 1)
assert(ClassicCastBarCharDB.scale == 1)
assert(db.point == nil and db.relativePoint == nil and db.x == nil and db.y == nil)
print("CLASSIC_CASTBAR_WORKFLOW", "reset")
print("CLASSIC_CASTBAR_WORKFLOW", "DONE")
