local frame = assert(CustomArrowFrame, 'addon arrow frame missing')
assert(frame:IsVisible(), 'addon did not show its arrow')
local texture = assert(frame.texture)
local output = io.stdout
local function mark(name, value)
    output:write('MINIMAP_FACING\t' .. name .. '\t' .. tostring(value) .. '\n')
    output:flush()
end
local function check_rotation(expected)
    local actual = texture:GetRotation()
    assert(math.abs(actual - expected) < 0.000001, 'arrow rotation differs from modeled facing')
    mark('rotation', actual)
end
C_CVar.SetCVar('rotateMinimap', '0')
A_Admin.SetPlayerFacing(0.5)
C_Timer.After(0.2, function()
    assert(GetPlayerFacing() == 0.5)
    check_rotation(0.5)
    A_Admin.SetPlayerFacing(2.5)
    C_Timer.After(0.2, function()
        assert(GetPlayerFacing() == 2.5)
        check_rotation(2.5)
        A_Admin.SetPlayerFacing(nil)
        C_Timer.After(0.2, function()
            assert(GetPlayerFacing() == nil)
            check_rotation(2.5)
            mark('DONE', true)
        end)
    end)
end)
