local name, title, notes, loadable, reason = C_AddOns.GetAddOnInfo('DBM-GUI')
local loading, loaded = C_AddOns.IsAddOnLoaded('DBM-GUI')
print('DBM_LOD_BEFORE', tostring(name), tostring(loadable), tostring(reason), tostring(loading), tostring(loaded), tostring(C_AddOns.IsAddOnLoadOnDemand('DBM-GUI')), tostring(DBM_GUI))
assert(name == 'DBM-GUI', 'missing metadata')
assert(C_AddOns.IsAddOnLoadOnDemand('DBM-GUI'), 'missing LoD flag')
assert(C_AddOns.GetAddOnDependencies('DBM-GUI') == 'DBM-Core', 'dependency mismatch')
assert(not loading and not loaded and DBM_GUI == nil, 'LoD code eagerly executed')
local ok, why = C_AddOns.LoadAddOn('DBM-GUI')
loading, loaded = C_AddOns.IsAddOnLoaded('DBM-GUI')
print('DBM_LOD_AFTER', tostring(ok), tostring(why), tostring(loading), tostring(loaded), tostring(DBM_GUI), tostring(DBM_GUI_OptionsFrame))
assert(ok and loading and loaded, 'explicit load failed')
assert(DBM_GUI and DBM_GUI_OptionsFrame, 'module observables missing')
print('DBM_GUI_LOD_METADATA_AND_LOAD_PASS')
