-- Native PTR capture; structures run only. No secrets run included.
return {
[1]={
["client"]={
["build"]="69594",
["interface"]=120105,
["version"]="12.1.5",
},
["kind"]="structures",
["matchesPinnedBuild"]=true,
["observations"]={
[1]={
["label"]="GetBuildInfo",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="12.1.5",
},
[2]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="69594",
},
[3]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="Aug 28 2026",
},
[4]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=120105,
},
[5]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="",
},
[6]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]=" ",
},
},
["returnCount"]=6,
},
[2]={
["label"]="GetLocale",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="enUS",
},
},
["returnCount"]=1,
},
[3]={
["label"]="timestamp",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=1789179121,
},
},
["returnCount"]=1,
},
[4]={
["label"]="issecure:direct",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="boolean",
["secret"]=false,
["value"]=false,
},
},
["returnCount"]=1,
},
[5]={
["label"]="issecure:securecallfunction",
["mode"]="securecallfunction",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="boolean",
["secret"]=false,
["value"]=false,
},
},
["returnCount"]=1,
},
[6]={
["label"]="globals:CreateRegionParams",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="nil",
["secret"]=false,
},
},
["returnCount"]=1,
},
[7]={
["label"]="globals:TimedSignalMapEntry",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="nil",
["secret"]=false,
},
},
["returnCount"]=1,
},
[8]={
["label"]="regions:owner:create",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="table",
["secret"]=false,
},
},
["returnCount"]=1,
},
[9]={
["label"]="regions:owner:Hide",
["mode"]="direct",
["ok"]=true,
["results"]={
},
["returnCount"]=0,
},
[10]={
["label"]="regions:Texture:method",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="function",
["secret"]=false,
},
},
["returnCount"]=1,
},
[11]={
["label"]="regions:Texture:positional:plain:create",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="table",
["secret"]=false,
},
},
["returnCount"]=1,
},
[12]={
["label"]="regions:Texture:positional:plain:GetName",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="Ptr125RemainingProbeTexture2",
},
},
["returnCount"]=1,
},
[13]={
["label"]="regions:Texture:positional:plain:GetDrawLayer",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="OVERLAY",
},
[2]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=3,
},
},
["returnCount"]=2,
},
[14]={
["label"]="regions:Texture:positional:plain:GetSize",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=0,
},
[2]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=0,
},
},
["returnCount"]=2,
},
[15]={
["error"]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="bad argument #2 to '?' (Usage: local texture = self:CreateTexture(params))",
},
["label"]="regions:Texture:table:plain:create",
["mode"]="direct",
["ok"]=false,
["results"]={
},
},
[16]={
["label"]="regions:Texture:positional:template:create",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="table",
["secret"]=false,
},
},
["returnCount"]=1,
},
[17]={
["label"]="regions:Texture:positional:template:GetName",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="Ptr125RemainingProbeTexture4",
},
},
["returnCount"]=1,
},
[18]={
["label"]="regions:Texture:positional:template:GetDrawLayer",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="OVERLAY",
},
[2]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=3,
},
},
["returnCount"]=2,
},
[19]={
["label"]="regions:Texture:positional:template:GetSize",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=16.999998092651371,
},
[2]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=19,
},
},
["returnCount"]=2,
},
[20]={
["error"]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="bad argument #2 to '?' (Usage: local texture = self:CreateTexture(params))",
},
["label"]="regions:Texture:table:template:create",
["mode"]="direct",
["ok"]=false,
["results"]={
},
},
[21]={
["label"]="regions:FontString:method",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="function",
["secret"]=false,
},
},
["returnCount"]=1,
},
[22]={
["label"]="regions:FontString:positional:plain:create",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="table",
["secret"]=false,
},
},
["returnCount"]=1,
},
[23]={
["label"]="regions:FontString:positional:plain:GetName",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="Ptr125RemainingProbeFontString6",
},
},
["returnCount"]=1,
},
[24]={
["label"]="regions:FontString:positional:plain:GetDrawLayer",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="OVERLAY",
},
[2]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=0,
},
},
["returnCount"]=2,
},
[25]={
["label"]="regions:FontString:positional:plain:GetSize",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=1.00000011920929,
},
[2]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=1.00000011920929,
},
},
["returnCount"]=2,
},
[26]={
["error"]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="Interface/AddOns/Ptr125RemainingProbe/Core.lua:61: bad argument #2 to 'fn' (Usage: local line = self:CreateFontString([name, drawLayer, templateName]))",
},
["label"]="regions:FontString:table:plain:create",
["mode"]="direct",
["ok"]=false,
["results"]={
},
},
[27]={
["label"]="regions:FontString:positional:template:create",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="table",
["secret"]=false,
},
},
["returnCount"]=1,
},
[28]={
["label"]="regions:FontString:positional:template:GetName",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="Ptr125RemainingProbeFontString8",
},
},
["returnCount"]=1,
},
[29]={
["label"]="regions:FontString:positional:template:GetDrawLayer",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="OVERLAY",
},
[2]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=0,
},
},
["returnCount"]=2,
},
[30]={
["label"]="regions:FontString:positional:template:GetSize",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=23.000001907348629,
},
[2]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=28.999998092651371,
},
},
["returnCount"]=2,
},
[31]={
["error"]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="Interface/AddOns/Ptr125RemainingProbe/Core.lua:61: bad argument #2 to 'fn' (Usage: local line = self:CreateFontString([name, drawLayer, templateName]))",
},
["label"]="regions:FontString:table:template:create",
["mode"]="direct",
["ok"]=false,
["results"]={
},
},
[32]={
["label"]="regions:Line:method",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="function",
["secret"]=false,
},
},
["returnCount"]=1,
},
[33]={
["label"]="regions:Line:positional:plain:create",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="table",
["secret"]=false,
},
},
["returnCount"]=1,
},
[34]={
["label"]="regions:Line:positional:plain:GetName",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="Ptr125RemainingProbeLine10",
},
},
["returnCount"]=1,
},
[35]={
["label"]="regions:Line:positional:plain:GetDrawLayer",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="OVERLAY",
},
[2]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=3,
},
},
["returnCount"]=2,
},
[36]={
["label"]="regions:Line:positional:plain:GetSize",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=0,
},
[2]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=0,
},
},
["returnCount"]=2,
},
[37]={
["error"]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="bad argument #2 to '?' (Usage: local line = self:CreateLine(params))",
},
["label"]="regions:Line:table:plain:create",
["mode"]="direct",
["ok"]=false,
["results"]={
},
},
[38]={
["label"]="regions:MaskTexture:method",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="function",
["secret"]=false,
},
},
["returnCount"]=1,
},
[39]={
["label"]="regions:MaskTexture:positional:plain:create",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="table",
["secret"]=false,
},
},
["returnCount"]=1,
},
[40]={
["label"]="regions:MaskTexture:positional:plain:GetName",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="Ptr125RemainingProbeMaskTexture12",
},
},
["returnCount"]=1,
},
[41]={
["label"]="regions:MaskTexture:positional:plain:GetDrawLayer",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="OVERLAY",
},
[2]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=3,
},
},
["returnCount"]=2,
},
[42]={
["label"]="regions:MaskTexture:positional:plain:GetSize",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=0,
},
[2]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=0,
},
},
["returnCount"]=2,
},
[43]={
["error"]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="bad argument #2 to '?' (Usage: local maskTexture = self:CreateMaskTexture(params))",
},
["label"]="regions:MaskTexture:table:plain:create",
["mode"]="direct",
["ok"]=false,
["results"]={
},
},
[44]={
["label"]="structures:regions",
["mode"]="direct",
["ok"]=true,
["results"]={
},
["returnCount"]=0,
},
[45]={
["label"]="signals:factory",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="function",
["secret"]=false,
},
},
["returnCount"]=1,
},
[46]={
["label"]="signals:create",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="userdata",
["secret"]=false,
},
},
["returnCount"]=1,
},
[47]={
["label"]="signals:clock",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=73762.093000000008,
},
},
["returnCount"]=1,
},
[48]={
["label"]="signals:deadline",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=74362.093000000008,
},
},
["returnCount"]=1,
},
[49]={
["label"]="signals:SignalAt",
["mode"]="direct",
["ok"]=true,
["results"]={
},
["returnCount"]=0,
},
[50]={
["label"]="signals:HasSignal",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="boolean",
["secret"]=false,
["value"]=true,
},
},
["returnCount"]=1,
},
[51]={
["label"]="signals:GetSignalTime",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=74362.093000000008,
},
},
["returnCount"]=1,
},
[52]={
["label"]="signals:GetNextSignal",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=17,
},
[2]={
["accessible"]=true,
["kind"]="number",
["secret"]=false,
["value"]=74362.093000000008,
},
},
["returnCount"]=2,
},
[53]={
["label"]="signals:first-kind",
["mode"]="direct",
["ok"]=true,
["results"]={
[1]={
["accessible"]=true,
["kind"]="string",
["secret"]=false,
["truncated"]=false,
["value"]="number",
},
},
["returnCount"]=1,
},
[54]={
["label"]="structures:signals",
["mode"]="direct",
["ok"]=true,
["results"]={
},
["returnCount"]=0,
},
[55]={
["label"]="action:structures",
["mode"]="direct",
["ok"]=true,
["results"]={
},
["returnCount"]=0,
},
[56]={
["label"]="cleanup:structures-signals",
["mode"]="direct",
["ok"]=true,
["results"]={
},
["returnCount"]=0,
},
[57]={
["label"]="cleanup:structures-owner",
["mode"]="direct",
["ok"]=true,
["results"]={
},
["returnCount"]=0,
},
},
["probeVersion"]=1,
["status"]="recorded",
["target"]={
["build"]="69594",
["interface"]=120105,
["version"]="12.1.5",
},
},
}
