use super::*;

struct DefaultMapSeed {
    ui_map_id: i32,
    name: &'static str,
    map_type: i32,
    parent_map_id: i32,
    art_id: i32,
    child_map_ids: &'static [i32],
}

const DEFAULT_MAP_SEEDS: &[DefaultMapSeed] = &[
    // UiMap.db2: 946 is Cosmic (type 0, no parent), 947 is Azeroth (type 1,
    // parent 946). They were swapped here for a long time.
    DefaultMapSeed {
        ui_map_id: 946,
        name: "Cosmic",
        map_type: 0,
        parent_map_id: 0,
        art_id: 0,
        child_map_ids: &[947],
    },
    DefaultMapSeed {
        ui_map_id: 947,
        name: "Azeroth",
        map_type: 1,
        parent_map_id: 946,
        art_id: 0,
        child_map_ids: &[13],
    },
    DefaultMapSeed {
        ui_map_id: 13,
        name: "Eastern Kingdoms",
        map_type: 2,
        parent_map_id: 947,
        art_id: 62,
        child_map_ids: &[84],
    },
    DefaultMapSeed {
        ui_map_id: 1,
        name: "Dun Morogh",
        map_type: 3,
        parent_map_id: 0,
        art_id: 12,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 84,
        name: "Stormwind City",
        map_type: 3,
        parent_map_id: 13,
        art_id: 104,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 23,
        name: "Eastern Plaguelands",
        map_type: 3,
        parent_map_id: 13,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 42,
        name: "Deadwind Pass",
        map_type: 3,
        parent_map_id: 13,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 50,
        name: "Northern Stranglethorn",
        map_type: 3,
        parent_map_id: 13,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 70,
        name: "Dustwallow Marsh",
        map_type: 3,
        parent_map_id: 12,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 75,
        name: "Caverns of Time",
        map_type: 5,
        parent_map_id: 71,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 91,
        name: "Alterac Valley",
        map_type: 3,
        parent_map_id: 0,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 93,
        name: "Arathi Basin",
        map_type: 3,
        parent_map_id: 0,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 121,
        name: "Eye of the Storm",
        map_type: 3,
        parent_map_id: 0,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 128,
        name: "Strand of the Ancients",
        map_type: 3,
        parent_map_id: 0,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 169,
        name: "Isle of Conquest",
        map_type: 3,
        parent_map_id: 0,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 108,
        name: "Terokkar Forest",
        map_type: 3,
        parent_map_id: 101,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 109,
        name: "Netherstorm",
        map_type: 3,
        parent_map_id: 101,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 114,
        name: "Borean Tundra",
        map_type: 3,
        parent_map_id: 113,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 117,
        name: "Howling Fjord",
        map_type: 3,
        parent_map_id: 113,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 118,
        name: "Icecrown",
        map_type: 3,
        parent_map_id: 113,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 120,
        name: "The Storm Peaks",
        map_type: 3,
        parent_map_id: 113,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 122,
        name: "Isle of Quel'Danas",
        map_type: 3,
        parent_map_id: 13,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 123,
        name: "Wintergrasp",
        map_type: 3,
        parent_map_id: 113,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 198,
        name: "Mount Hyjal",
        map_type: 3,
        parent_map_id: 12,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 207,
        name: "Deepholm",
        map_type: 3,
        parent_map_id: 276,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 249,
        name: "Uldum",
        map_type: 3,
        parent_map_id: 12,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 379,
        name: "Kun-Lai Summit",
        map_type: 3,
        parent_map_id: 424,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 390,
        name: "Vale of Eternal Blossoms",
        map_type: 3,
        parent_map_id: 424,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 504,
        name: "Isle of Thunder",
        map_type: 3,
        parent_map_id: 424,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 534,
        name: "Tanaan Jungle",
        map_type: 3,
        parent_map_id: 572,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 543,
        name: "Gorgrond",
        map_type: 3,
        parent_map_id: 572,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 646,
        name: "Broken Shore",
        map_type: 3,
        parent_map_id: 619,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 680,
        name: "Suramar",
        map_type: 3,
        parent_map_id: 619,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 862,
        name: "Zuldazar",
        map_type: 3,
        parent_map_id: 875,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 863,
        name: "Nazmir",
        map_type: 3,
        parent_map_id: 875,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 885,
        name: "Antoran Wastes",
        map_type: 3,
        parent_map_id: 882,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 895,
        name: "Tiragarde Sound",
        map_type: 3,
        parent_map_id: 876,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 2248,
        name: "Isle of Dorn",
        map_type: 3,
        parent_map_id: 947, // Azeroth: the nearest seeded ancestor (UiMap.db2 says 2274 Khaz Algar, not seeded)
        art_id: 5920,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 1409,
        name: "Exile's Reach",
        map_type: 3,
        parent_map_id: 0,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 1462,
        name: "Mechagon Island",
        map_type: 3,
        parent_map_id: 876,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 1527,
        name: "Uldum",
        map_type: 3,
        parent_map_id: 12,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 1530,
        name: "Vale of Eternal Blossoms",
        map_type: 3,
        parent_map_id: 424,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 1533,
        name: "Bastion",
        map_type: 3,
        parent_map_id: 1550,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 1543,
        name: "The Maw",
        map_type: 3,
        parent_map_id: 1550,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 1550,
        name: "The Shadowlands",
        map_type: 2,
        parent_map_id: 946, // Cosmic, as in UiMap.db2
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 1670,
        name: "Oribos",
        map_type: 3,
        parent_map_id: 0,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 1970,
        name: "Zereth Mortis",
        map_type: 3,
        parent_map_id: 1550,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 2200,
        name: "Emerald Dream",
        map_type: 3,
        parent_map_id: 1978,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 2214,
        name: "The Ringing Deeps",
        map_type: 3,
        parent_map_id: 2274,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 2255,
        name: "Azj-Kahet",
        map_type: 3,
        parent_map_id: 2275,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 2346,
        name: "Undermine",
        map_type: 3,
        parent_map_id: 2274,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 2371,
        name: "K'aresh",
        map_type: 3,
        parent_map_id: 2274,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 2395,
        name: "Eversong Woods",
        map_type: 3,
        parent_map_id: 13,
        art_id: 0,
        child_map_ids: &[],
    },
    DefaultMapSeed {
        ui_map_id: 2424,
        name: "Isle of Quel'Danas",
        map_type: 3,
        parent_map_id: 13,
        art_id: 0,
        child_map_ids: &[],
    },
];

/// Seed the `SimState.maps` table with the handful of ui-map ids
/// commonly referenced by Blizzard UI and bundled addons. Retail ids from
/// UiMap.db2 references mirrored by Warcraft Wiki / Wowpedia.
pub(in crate::lua_api::state) fn default_maps() -> HashMap<i32, MapData> {
    DEFAULT_MAP_SEEDS.iter().map(default_map_entry).collect()
}

fn default_map_entry(seed: &DefaultMapSeed) -> (i32, MapData) {
    let map = MapData {
        ui_map_id: seed.ui_map_id,
        name: seed.name.into(),
        map_type: seed.map_type,
        parent_map_id: seed.parent_map_id,
        art_id: seed.art_id,
        flags: 0,
        child_map_ids: seed.child_map_ids.to_vec(),
        child_rects: Vec::new(),
        rect_on_parent: None,
    };

    (map.ui_map_id, map)
}
