#!/usr/bin/env python3
"""Generate sparse base aura-secrecy attributes from pinned client exports."""

import argparse
import csv
import hashlib
import json
from pathlib import Path

FLAG_PATH = "meta/flags/SpellAttributes15.dbdf"
ALWAYS_NAME = "AURA_ALWAYS_SECRET"
NEVER_NAME = "AURA_NEVER_SECRET"
REQUIRED_COLUMNS = {"SpellID", "DifficultyID", "Attributes_15"}


def read_flag_definitions(path):
    definitions = {}
    for line in path.read_text().splitlines():
        fields = line.split()
        if len(fields) == 2 and fields[1] in (ALWAYS_NAME, NEVER_NAME):
            definitions[fields[1]] = int(fields[0], 0)
    if set(definitions) != {ALWAYS_NAME, NEVER_NAME}:
        raise ValueError(f"{path}: missing aura-secrecy flag definitions")
    if definitions[ALWAYS_NAME] & definitions[NEVER_NAME]:
        raise ValueError(f"{path}: aura-secrecy flags overlap")
    return definitions[ALWAYS_NAME], definitions[NEVER_NAME]


def read_base_aura_flags(path, always, never):
    base_flags = {}
    with path.open(newline="") as source:
        rows = csv.DictReader(source)
        missing = REQUIRED_COLUMNS - set(rows.fieldnames or [])
        if missing:
            raise ValueError(f"{path}: missing columns {sorted(missing)}")
        for row in rows:
            if int(row["DifficultyID"]) != 0:
                continue
            spell_id = int(row["SpellID"])
            flags = (int(row["Attributes_15"]) & 0xFFFFFFFF) & (always | never)
            if spell_id in base_flags and base_flags[spell_id] != flags:
                raise ValueError(f"{path}: conflicting base rows for spell {spell_id}")
            base_flags[spell_id] = flags
    return sorted((spell_id, flags) for spell_id, flags in base_flags.items() if flags)


def verify_flag_provenance(flags_path, tree_path):
    tree = json.loads(tree_path.read_text())
    entries = [entry for entry in tree["tree"] if entry["path"] == FLAG_PATH]
    if len(entries) != 1:
        raise ValueError(f"{tree_path}: expected one {FLAG_PATH} entry")
    data = flags_path.read_bytes()
    blob = b"blob " + str(len(data)).encode("ascii") + b"\0" + data
    actual = hashlib.sha1(blob).hexdigest()
    if actual != entries[0]["sha"]:
        raise ValueError(f"{flags_path}: contents do not match pinned definition blob")
    return tree["sha"], actual


def render_rust(rows, always, never, build, csv_hash):
    lines = [
        "//! Generated by tools/gen_spell_aura_secrecy.py; do not edit manually.",
        f"//! Client export: {build}; SpellMisc SHA-256: {csv_hash}.",
        "//! Both native flags are retained; no precedence is inferred.",
        "",
        f"pub const AURA_ALWAYS_SECRET: u32 = 0x{always:08x};",
        f"pub const AURA_NEVER_SECRET: u32 = 0x{never:08x};",
        "",
        "pub const SPELL_AURA_SECRECY_FLAGS: &[(u32, u32)] = &[",
    ]
    lines.extend(f"    ({spell_id}, 0x{flags:08x})," for spell_id, flags in rows)
    lines.extend([
        "];",
        "",
        "pub fn aura_flags(spell_id: u32) -> u32 {",
        "    SPELL_AURA_SECRECY_FLAGS",
        "        .binary_search_by_key(&spell_id, |&(id, _)| id)",
        "        .map(|index| SPELL_AURA_SECRECY_FLAGS[index].1)",
        "        .unwrap_or(0)",
        "}",
        "",
    ])
    return "\n".join(lines)


def generate(args):
    always, never = read_flag_definitions(args.flags)
    tree_sha, blob_sha = verify_flag_provenance(args.flags, args.definitions_tree)
    rows = read_base_aura_flags(args.input, always, never)
    csv_hash = hashlib.sha256(args.input.read_bytes()).hexdigest()
    provenance = {
        "build": args.build,
        "spell_misc_url": f"https://wago.tools/db2/SpellMisc/csv?build={args.build}",
        "spell_misc_sha256": csv_hash,
        "definitions_repository": "https://github.com/wowdev/WoWDBDefs",
        "definitions_tree_sha": tree_sha,
        "definitions_path": FLAG_PATH,
        "definitions_blob_sha": blob_sha,
        "difficulty_id": 0,
        "flagged_spells": len(rows),
        "always_only": sum(flags == always for _, flags in rows),
        "never_only": sum(flags == never for _, flags in rows),
        "ambiguous_spell_ids": [spell_id for spell_id, flags in rows if flags == always | never],
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_rust(rows, always, never, args.build, csv_hash))
    args.provenance.parent.mkdir(parents=True, exist_ok=True)
    args.provenance.write_text(json.dumps(provenance, indent=2) + "\n")
    print(f"Generated {len(rows)} sparse base aura-secrecy rows")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--flags", type=Path, required=True)
    parser.add_argument("--definitions-tree", type=Path, required=True)
    parser.add_argument("--build", required=True)
    parser.add_argument("--output", type=Path, default=Path("data/spell_aura_secrecy.rs"))
    parser.add_argument("--provenance", type=Path, default=Path("data/spell_aura_secrecy.provenance.json"))
    generate(parser.parse_args())


if __name__ == "__main__":
    main()
